[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
compute_share = "Afn7mniibRXcMvergvr1Q6BnF3vEDkJop1XSHrTXJLTR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/phamkhanh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
